spring:
  main:
    allow-bean-definition-overriding: true
  restTemplate:
    messageConverters:
      - jackson
      - xml
    requestFactory:
      timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lab:
            non_contextual_creation: true
    datasource:
      hikari:
        connectionTimeout: 20000
        maximumPoolSize: 5
        poolName: HikariPoolZZZ

client:
  dog:
    url: https://api.thedogapi.com/v1
    api_key: live_d1YNv0nPUFXB5rhYlsq83xtfpdWz0omzMpz7ozAaPKJzRCj8OUIeQXe5YNAtlFq1
  cat:
    url: https://api.thecatapi.com/v1
    api_key: live_BjF84VFjeLAmGdoNp7lYTJTK7MwQVxD59nmOJ7bifHlZu8hyhvUZSqvgasb5PjZa